# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/Ahmed/Documents/L2 SPI/C/Personnels/BlackJack-C-SDL"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/Ahmed/Documents/L2 SPI/C/Personnels/BlackJack-C-SDL"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/Ahmed/Documents/L2 SPI/C/Personnels/BlackJack-C-SDL/CMakeFiles" "/Users/Ahmed/Documents/L2 SPI/C/Personnels/BlackJack-C-SDL/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/Ahmed/Documents/L2 SPI/C/Personnels/BlackJack-C-SDL/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blackjack

# Build rule for target.
blackjack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blackjack
.PHONY : blackjack

# fast build rule for target.
blackjack/fast:
	$(MAKE) -f CMakeFiles/blackjack.dir/build.make CMakeFiles/blackjack.dir/build
.PHONY : blackjack/fast

#=============================================================================
# Target rules for targets named ESDL

# Build rule for target.
ESDL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ESDL
.PHONY : ESDL

# fast build rule for target.
ESDL/fast:
	$(MAKE) -f deps/easysdl/CMakeFiles/ESDL.dir/build.make deps/easysdl/CMakeFiles/ESDL.dir/build
.PHONY : ESDL/fast

src/bj_engine.o: src/bj_engine.c.o
.PHONY : src/bj_engine.o

# target to build an object file
src/bj_engine.c.o:
	$(MAKE) -f CMakeFiles/blackjack.dir/build.make CMakeFiles/blackjack.dir/src/bj_engine.c.o
.PHONY : src/bj_engine.c.o

src/bj_engine.i: src/bj_engine.c.i
.PHONY : src/bj_engine.i

# target to preprocess a source file
src/bj_engine.c.i:
	$(MAKE) -f CMakeFiles/blackjack.dir/build.make CMakeFiles/blackjack.dir/src/bj_engine.c.i
.PHONY : src/bj_engine.c.i

src/bj_engine.s: src/bj_engine.c.s
.PHONY : src/bj_engine.s

# target to generate assembly for a file
src/bj_engine.c.s:
	$(MAKE) -f CMakeFiles/blackjack.dir/build.make CMakeFiles/blackjack.dir/src/bj_engine.c.s
.PHONY : src/bj_engine.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/blackjack.dir/build.make CMakeFiles/blackjack.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/blackjack.dir/build.make CMakeFiles/blackjack.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/blackjack.dir/build.make CMakeFiles/blackjack.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... blackjack"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ESDL"
	@echo "... src/bj_engine.o"
	@echo "... src/bj_engine.i"
	@echo "... src/bj_engine.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

